name: optima

{% set python_version = os.environ.get("PY_VER", "3.12") %}

channels:
  - conda-forge

dependencies:
  - catch2 =2
  - ccache
  - clangxx  # [linux]
  - clangxx_osx-64  # [osx and not arm64]
  - clangxx_osx-arm64  # [osx and arm64]
  - cmake
  - eigen
  - gxx_linux-64  # [linux]
  - lld  # [unix]
  - make
  - ninja
  - numpy
  - pip
  - pybind11
  - pybind11-abi
  - pybind11-stubgen
  - pytest
  - pytest-xdist
  - python ={{ python_version }}
  - vs2019_win-64  # [win]
  - pip:
    - mkdocs
    - mkdocs-macros-plugin
    - mkdocs-material
    - pytest-regressions
