name: linux

on:
  push:
    branches:
      - master

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      os: Linux-x86_64
      configuration: Release

    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Configure
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv
          source activate optima
          cmake -S . -B .build
      - name: Build
        shell: bash -l {0}
        run: cmake --build .build --config ${{ env.configuration }} --parallel 3
      - name: Install
        shell: bash -l {0}
        run: cmake --build .build --config ${{ env.configuration }} --target install
      - name: Tests
        shell: bash -l {0}
        # run: |
        #   export PYTHONPATH=$PWD/.build/python/package/build/lib
        #   pytest -n auto -x
        run: |
          source activate optima
          cmake --build .build --config ${{ env.configuration }} --target tests
