name: osx

on:
  push:
    branches:
      - master

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:

    runs-on: macOS-latest
    env:
      os: MacOSX-x86_64
    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Build, Install & Test
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda update -q conda
          conda info -a
          conda devenv
          source activate optima
          conda list
          cmake -DTESTS=ON -P install
