name: windows

on:
  push:
    branches:
      - master

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:

    runs-on: windows-latest
    env:
      configuration: Release
    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ''
      - name: Configure
        shell: cmd /C CALL {0}
        run: |
          conda install -c conda-forge conda-devenv
          conda info -a
          conda devenv
          conda activate optima
          clcache -s
          clcache -z
          cmake -S . -B .build
      - name: Build
        shell: cmd /C CALL {0}
        run: |
          conda activate optima
          cmake --build .build --config ${{ env.configuration }}
          clcache -s
      - name: Install
        shell: cmd /C CALL {0}
        run: |
          conda activate optima
          cmake --build .build --config ${{ env.configuration }} --target install
      - name: Tests
        shell: cmd /C CALL {0}
        run: |
          conda activate optima
          cmake --build .build --config ${{ env.configuration }} --target tests
